---
title: 'Statistical Inference'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
params:
  author: 'Anderson H Uyekita'
  course: 'Statistical Inference'
  course_url: 'https://www.coursera.org/learn/statistical-inference'
  specialization: 'Data Science: Statistics and Machine Learning Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-statistics-machine-learning'
  instructor: 'Brian Caffo'
  course_start: !r lubridate::ymd('2022/06/29', tz = "America/Sao_Paulo")
  course_finish: !r lubridate::ymd('2022/07/05', tz = "America/Sao_Paulo")
  certificate_url: './'
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(params$certificate_url != "./") {sprintf(fmt = "* &#x1F393; [Certificate](%s)", params$certificate_url)}`

--------------------------------------------------------------------------------

#### Assignments & Deliverables

* [&#x1F680; Course Project -- Part 1 Repository](https://github.com/AndersonUyekita/statistical-inference_course-project/tree/main/Part%201)
* [&#x1F680; Course Project -- Part 2 Repository](https://github.com/AndersonUyekita/statistical-inference_course-project/tree/main/Part%202)
* [&#x1F4DD; Quiz 1](./Week 1/quiz-1_statistical-inference.md)
* [&#x1F4DD; Quiz 2](./Week 2/quiz-2_statistical-inference.md)
* [&#x1F4DD; Quiz 3](./Week 3/quiz-3_statistical-inference.md)
* [&#x1F4DD; Quiz 4](./Week 4/quiz-4_statistical-inference.md)

#### Class Notes

* [&#x1F4C6; Week 1](./Week 1)
* [&#x1F4C6; Week 2](./Week 2)
* [&#x1F4C6; Week 3](./Week 3)
* [&#x1F4C6; Week 4](./Week 4)
* [&#x1F4D1; Course Textbook Notes](./book)

#### Course Description

In this class students will learn the fundamentals of statistical inference. Students will receive a broad overview of the goals, assumptions and modes of performing statistical inference. Students will be able to perform inferential tasks in highly targeted settings and will be able to use the skills developed as a roadmap for more complex inferential challenges.


#### Course Syllabus

* Introduction
* Probability
* Conditional Probability
* Expectations
* Variance
* Common Distributions
* Asymptotics
* T confidence intervals
* Hypothesis testing
* P-values
* Power
* Multiple Testing
* Resampling

#### Course Textbook

The book [&#x1F4D4; Statistical inference for data science](./book/statistical-inference-for-data-science.pdf) covers the lecture material in this course.

#### Course Projects

The Course Project is an opportunity to demonstrate the skills you have learned during the course. It is graded through peer assessment.


