---
title: '`Quiz 4` Statistical Inference'
author: '`r if(knitr::is_html_output()) {"&#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Anderson H Uyekita"} else {NULL}`'
output:
  github_document: default
  html_document:
    self_contained: true
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
      smooth_scroll: true
params:
  author: 'Anderson H Uyekita'
  course: 'Statistical Inference'
  course_url: 'https://www.coursera.org/learn/statistical-inference'
  specialization: 'Data Science: Statistics and Machine Learning Specialization'
  specialization_url: 'https://www.coursera.org/specializations/data-science-statistics-machine-learning'
  instructor: 'Brian Caffo'
  course_start: !r lubridate::ymd('2022/07/01', tz = "America/Sao_Paulo")
  course_finish: !r lubridate::today(tzone = "America/Sao_Paulo")
  week: ' Week 4'
always_allow_html: true
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE, message = FALSE, warning = FALSE)
library(rmarkdown)
library(lubridate)
```

`r if(!knitr::is_html_output()) {sprintf(fmt = "* &#x1f468;&#x1F3FB;&#x200d;&#x1f4bb; Author: %s", params$author)}`
`r sprintf(fmt = "* &#x1f4da; Specialization: [%s](%s){target='_blank' rel='noopener'}", params$specialization, params$specialization_url)`
`r sprintf(fmt = "* &#x1f4d6; Course: [%s](%s){target='_blank' rel='noopener'}", params$course, params$course_url)`
    `r sprintf(fmt = "* &#x1F9D1;&#x200d;&#x1F3EB; Instructor: %s", params$instructor)`
`r sprintf(fmt = "* &#x1F4C6; %s", params$week)`
    `r sprintf(fmt = "* &#x1F6A6; Start: %s", format(params$course_start, "%A, %d %B %Y"))`
    `r sprintf(fmt = "* &#x1F3C1; Finish: %s", format(params$course_finish, "%A, %d %B %Y"))`
`r if(!knitr::is_html_output()) {"* &#x1F30E; Rpubs: [Interactive Document](https://rpubs.com/AndersonUyekita/quiz-4_statistical-inference)"}else{"* &#x1F4E6; Github Repository: [Static Document](https://github.com/AndersonUyekita/statistical-inference/blob/main/Week%204/quiz-4_statistical-inference.md){target='_blank' rel='noopener'}"}`

--------------------------------------------------------------------------------

## Question 1

A pharmaceutical company is interested in testing a potential blood pressure lowering medication. Their first examination considers only subjects that received the medication at baseline then two weeks later. The data are as follows (SBP in mmHg)

|Subject|Baseline|Week 2|
|:-----:|:------:|:----:|
|1      |  140   |  132 |
|2      |  138   |  135 |
|3      |  150   |  151 |
|4      |  148   |  146 |
|5      |  135   |  130 |

Consider testing the hypothesis that there was a mean reduction in blood pressure? Give the P-value for the associated two sided T test. 

_(Hint, consider that the observations are paired.)_

- [ ] 0.10
- [ ] 0.087
- [ ] 0.05
- [ ] 0.043

**Answer**




## Question 2

A sample of 9 men yielded a sample average brain volume of 1,100cc and a standard deviation of 30cc. What is the complete set of values of $\mu_0$ that a test of  $H_0: \mu = \mu_0$ would fail to reject the null hypothesis in a two sided 5% Students t-test?

- [ ] 1081 to 1119
- [ ] 1031 to 1169
- [ ] 1080 to 1120
- [ ] 1077 to 1123

**Answer**





## Question 3

Researchers conducted a blind taste test of Coke versus Pepsi. Each of four people was asked which of two blinded drinks given in random order that they preferred. The data was such that 3 of the 4 people chose Coke. Assuming that this sample is representative, report a P-value for a test of the hypothesis that Coke is preferred to Pepsi using a one sided exact test.

- [ ] 0.62
- [ ] 0.005
- [ ] 0.10
- [ ] 0.31

**Answer**





## Question 4

Infection rates at a hospital above 1 infection per 100 person days at risk are believed to be too high and are used as a benchmark. A hospital that had previously been above the benchmark recently had 10 infections over the last 1,787 person days at risk. About what is the one sided P-value for the relevant test of whether the hospital is *below* the standard? 

- [ ] 0.22
- [ ] 0.03
- [ ] 0.52
- [ ] 0.11

**Answer**





## Question 5

Suppose that 18 obese subjects were randomized, 9 each, to a new diet pill and a placebo. Subjects’ body mass indices (BMIs) were measured at a baseline and again after having received the treatment or placebo for four weeks. The average difference from follow-up to the baseline (followup - baseline) was −3 kg/m2 for the treated group and 1 kg/m2 for the placebo group. The corresponding standard deviations of the differences was 1.5 kg/m2 for the treatment group and 1.8 kg/m2 for the placebo group. Does the change in BMI appear to differ between the treated and placebo groups?  Assuming normality of the underlying data and a common population variance, give a pvalue for a two sided t test.

- [ ] Less than 0.05, but larger than 0.01
- [ ] Less than 0.01
- [ ] Less than 0.10 but larger than 0.05
- [ ] Larger than 0.10

**Answer**




## Question 6

Brain volumes for 9 men yielded a 90% confidence interval of 1,077 cc to 1,123 cc. Would you reject in a two sided 5% hypothesis test of $H_0 :μ=1,078$? 

- [ ] Where does Brian come up with these questions?
- [ ] No you wouldn't reject.
- [ ] Yes you would reject.
- [ ] It's impossible to tell.

**Answer**




## Question 7

Researchers would like to conduct a study of $100$ healthy adults to detect a four year mean brain volume loss of $.01~mm^3$. Assume that the standard deviation of four year volume loss in this population is $.04~mm^3$. About what would be the power of the study for a $5\%$ one sided test versus a null hypothesis of no volume loss?

- [ ] 0.70
- [ ] 0.60
- [ ] 0.80
- [ ] 0.50

**Answer**




## Question 8

Researchers would like to conduct a study of  n n healthy adults to detect a four year mean brain volume loss of $.01~mm^3$. Assume that the standard deviation of four year volume loss in this population is $.04~mm^3$. About what would be the value of  n n needed for $90\%$ power of type one error rate of $5\%$ one sided test versus a null hypothesis of no volume loss?

- [ ] 120
- [ ] 180
- [ ] 160
- [ ] 140

**Answer**




## Question 9

As you increase the type one error rate, $\alpha$, what happens to power?

- [ ] No, for real, where does Brian come up with these problems?
- [ ] It's impossible to tell given the information in the problem.
- [ ] You will get smaller power.
- [ ] You will get larger power.

**Answer**




